Criada estrutura para departamentos
anakettl/ZenviaExperienceHackathon pull request #1
Opened 2020-07-18 22:55 UTC by anakettl

criar departamento

2020-07-18 23:29 UTC, bolicos requested changes

2020-07-18 23:29 UTC, analuciabolico commented on src/main/java/com/hackaton/backend/v1/department/repository/DepartmentRepository.java
> +public interface DepartmentRepository extends JpaRepository<Department, Long> {
```suggestion
@Repository
public interface DepartmentRepository extends JpaRepository<Department, Long> {
```

2020-07-18 23:29 UTC, analuciabolico commented on src/main/java/com/hackaton/backend/v1/department/repository/DepartmentRepository.java
> +public interface DepartmentRepository extends JpaRepository<Department, Long> {
alem de adicionar a anotacao tem que adicionar o import

2020-07-19 00:38 UTC, anakettl commented on src/main/java/com/hackaton/backend/v1/department/repository/DepartmentRepository.java
> +public interface DepartmentRepository extends JpaRepository<Department, Long> {
adicionado

2020-07-19 00:38 UTC, anakettl commented on src/main/java/com/hackaton/backend/v1/department/repository/DepartmentRepository.java
> +public interface DepartmentRepository extends JpaRepository<Department, Long> {
adicionado

2020-07-19 03:28 UTC, merged